[package]
name = "litmus"
version = "0.3.0"
edition = "2024"
license = "MIT"

[dependencies]
oxc_parser = ">=0.121.0"
oxc_allocator = ">=0.121.0"
oxc_ast = ">=0.121.0"
oxc_span = ">=0.121.0"
glob = ">=0.3.3"

[dev-dependencies]
tempfile = "3"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
# absolute paths
absolute_paths = "deny"
# idiomatic iterators
cast_possible_truncation = "deny"
redundant_closure_for_method_calls = "deny"
filter_map_next = "deny"
flat_map_option = "deny"
manual_filter_map = "deny"
manual_find_map = "deny"
# imports
wildcard_imports = "deny"
enum_glob_use = "deny"
# strings
str_to_string = "deny"
# arguments
needless_pass_by_value = "deny"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
